# Generated by Django 5.0.2 on 2024-03-28 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_articles_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
